services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=devDB
    volumes:
      - ./src/db/database.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: